# (POST /webhooks/hubspot/deals): Send an Upright profile to Slack 
#
# In production, this endpoint is triggered when new Company is assigned to a deal but locally we can test it with the post request below:
# First, for testing purposes create a new deal in Hubspot test environment and assign a company for the deal.
# Then, change the objectId below to the ID of the Deal from HubSpot and change the hubspothash to the HUBSPOT_HASH value from your env file
@objectId = "36062180357"
@hubspothash = c5ee1e9d136e77b527f182cf3aab6f5a3a19800f215de55d0f182fdf73775674

POST  http://0.0.0.0:3000/{{hubspothash}}/webhooks/hubspot/deals
Content-Type: application/json

{
    "objectType": "DEAL",
    "objectId": {{objectId}}
}

###
# (GET /deals/{id}/profile): Get an Upright profile by HubSpot deal ID
#
# This endpoint fetches Upright profile data for a given deal. Replace `dealId` below with an actual deal ID from your HubSpot test environment.
# Replace `dealshash` with the DEALS_HASH value from your environment file.

@dealId = 36062180357
@dealshash = b03c626bda14f009a693e48de55e5587257dfe1a8c2a00caaf9a7fd66724e7e0

GET  http://0.0.0.0:3000/{{dealshash}}/deals/{{dealId}}/profile


###
# (GET /deals/{id}/profileURL): Get the URL to an Upright profile by HubSpot deal ID
#
# This endpoint returns a URL to view the Upright profile associated with the given deal. Replace `dealId` below with a real ID from your HubSpot test setup.
# Replace `dealshash` with the DEALS_HASH value from your environment.

@dealId = 36062180357
@dealshash = b03c626bda14f009a693e48de55e5587257dfe1a8c2a00caaf9a7fd66724e7e0

GET http://0.0.0.0:3000/{{dealshash}}/deals/{{dealId}}/profileURL

###
# Test status

GET http://0.0.0.0:3000/status