name: impact-helper-api
on: push

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "16.x"
      - name: install dependencies
        run: npm ci
      - name: lint
        run: npx eslint
      - name: check format
        run: npx prettier --check .
      - name: build
        run: npm run build
      - name: test
        run: npm test
